// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh0617hROuFMeCHSz626w9AYZHK_sOOfo',
    appId: '1:798689657385:web:cf20985440ee6040d75238',
    messagingSenderId: '798689657385',
    projectId: 'e-commerce-35',
    authDomain: 'e-commerce-35.firebaseapp.com',
    storageBucket: 'e-commerce-35.appspot.com',
    measurementId: 'G-YCCYP51XCQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa2kfy_HLSC91M4nIMM8EuqdL9V5B8vgI',
    appId: '1:798689657385:android:03cd26ac334e3ddcd75238',
    messagingSenderId: '798689657385',
    projectId: 'e-commerce-35',
    storageBucket: 'e-commerce-35.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv-JHLQ76emJFpMnjs-dGQM4_jv0rZ7rA',
    appId: '1:798689657385:ios:ac4c6999fed8daf3d75238',
    messagingSenderId: '798689657385',
    projectId: 'e-commerce-35',
    storageBucket: 'e-commerce-35.appspot.com',
    iosClientId: '798689657385-lqoc9d2skdlsok8602eo1hbl0q99hnm1.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDv-JHLQ76emJFpMnjs-dGQM4_jv0rZ7rA',
    appId: '1:798689657385:ios:4b5808484cadddcdd75238',
    messagingSenderId: '798689657385',
    projectId: 'e-commerce-35',
    storageBucket: 'e-commerce-35.appspot.com',
    iosClientId: '798689657385-b39dhlskc6tvc7etj06hmr1joehgvdcl.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce.RunnerTests',
  );
}
